//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.12 at 11:40:03 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.product.dtos.webService/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package webservice.dtos.product;
