//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:35:38 PM EET 
//


package webservice.endpointrequestresponse.orderrequestresponse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import webservice.dtos.order.OrderItemDTOForCreation;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ordersBillingNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OrderItemDTOForCreation" type="{http://www.order.dtos.webService/}OrderItemDTOForCreation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ordersBillingNumber",
    "orderItemDTOForCreation"
})
@XmlRootElement(name = "AddOrderItemsRequest")
public class AddOrderItemsRequest {

    @XmlElement(required = true)
    protected String ordersBillingNumber;
    @XmlElement(name = "OrderItemDTOForCreation")
    protected List<OrderItemDTOForCreation> orderItemDTOForCreation;

    /**
     * Gets the value of the ordersBillingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdersBillingNumber() {
        return ordersBillingNumber;
    }

    /**
     * Sets the value of the ordersBillingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdersBillingNumber(String value) {
        this.ordersBillingNumber = value;
    }

    /**
     * Gets the value of the orderItemDTOForCreation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderItemDTOForCreation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderItemDTOForCreation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderItemDTOForCreation }
     * 
     * 
     */
    public List<OrderItemDTOForCreation> getOrderItemDTOForCreation() {
        if (orderItemDTOForCreation == null) {
            orderItemDTOForCreation = new ArrayList<OrderItemDTOForCreation>();
        }
        return this.orderItemDTOForCreation;
    }

}
