//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.27 at 01:35:38 PM EET 
//


package webservice.endpointrequestresponse.productrequestresponse;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the webservice.endpointrequestresponse.productrequestresponse package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: webservice.endpointrequestresponse.productrequestresponse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateProductRequest }
     * 
     */
    public CreateProductRequest createCreateProductRequest() {
        return new CreateProductRequest();
    }

    /**
     * Create an instance of {@link GetProductRequest }
     * 
     */
    public GetProductRequest createGetProductRequest() {
        return new GetProductRequest();
    }

    /**
     * Create an instance of {@link GetProductResponse }
     * 
     */
    public GetProductResponse createGetProductResponse() {
        return new GetProductResponse();
    }

    /**
     * Create an instance of {@link GetAllProductsRequest }
     * 
     */
    public GetAllProductsRequest createGetAllProductsRequest() {
        return new GetAllProductsRequest();
    }

    /**
     * Create an instance of {@link GetAllProductsResponse }
     * 
     */
    public GetAllProductsResponse createGetAllProductsResponse() {
        return new GetAllProductsResponse();
    }

    /**
     * Create an instance of {@link AddProductPricesRequest }
     * 
     */
    public AddProductPricesRequest createAddProductPricesRequest() {
        return new AddProductPricesRequest();
    }

    /**
     * Create an instance of {@link AddProductPricesResponse }
     * 
     */
    public AddProductPricesResponse createAddProductPricesResponse() {
        return new AddProductPricesResponse();
    }

    /**
     * Create an instance of {@link DeleteProductPricesRequest }
     * 
     */
    public DeleteProductPricesRequest createDeleteProductPricesRequest() {
        return new DeleteProductPricesRequest();
    }

    /**
     * Create an instance of {@link DeleteProductPricesResponse }
     * 
     */
    public DeleteProductPricesResponse createDeleteProductPricesResponse() {
        return new DeleteProductPricesResponse();
    }

    /**
     * Create an instance of {@link DeleteProductRequest }
     * 
     */
    public DeleteProductRequest createDeleteProductRequest() {
        return new DeleteProductRequest();
    }

}
